/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registro_ucompensar;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan D. R. Olivos
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Person[] visitors;
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        createRecordBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        saveRecordBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOutput = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro Museo UCompensar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(301, 301, 301))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        createRecordBtn.setText("Crear Nuevo Registro");
        createRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRecordBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Salir");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        saveRecordBtn.setText("Guardar Registro");
        saveRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRecordBtnActionPerformed(evt);
            }
        });

        tableOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "N° Identificación", "Edad", "Categoría Afilicación", "Valor Entrada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableOutput);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("N°Identificación");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Categoría Afilicación");

        jButton1.setText("Agregar Visitante");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total a Pagar");

        jTextField1.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createRecordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveRecordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(createRecordBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveRecordBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(exitBtn)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método llamado cuando se hace clic en el botón para crear un nuevo registro de visitantes.
     * Crea un nuevo registro de visitantes y muestra un resumen en un cuadro de diálogo.
     * Elimina todas las filas existentes en la tabla antes de agregar las nuevas.
     * @param evt El evento que desencadenó la acción
     */
    private void createRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRecordBtnActionPerformed
        // Obtiene el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tableOutput.getModel();

        // Crea un nuevo registro de visitantes
        visitors = createVisitorsRecord();

        // Elimina todas las filas existentes en la tabla
        removeAllRows(model);

        // Variables para calcular el total a pagar y el número de adultos
        StringBuilder infoToShow = new StringBuilder();
        double totalToPay = 0;
        int totalAdults = 0;

        // Itera sobre cada visitante para agregar sus datos a la tabla y calcular el total a pagar y el número de adultos
        for(Person visitor : visitors){
            infoToShow.append(String.format("%s: %.2f$\n", visitor.getName(), visitor.getEntryValue()));
            totalToPay += visitor.getEntryValue();

            // Agrega la nueva fila a la tabla
            addRowToTable(model, visitor);

            // Incrementa el contador de adultos si el visitante es mayor de edad
            if(visitor.getAge() >= 18)
                totalAdults++;
        }

        // Crea un mensaje de resumen con el total a pagar y la cantidad de adultos y menores de edad
        infoToShow.append(String.format("Total a pagar: %.2f\nVisitantes: %d\nTotal Adultos: %d\nTotal Menores de Edad: %d", totalToPay, visitors.length, totalAdults, (visitors.length - totalAdults)));

        // Muestra el mensaje de resumen en un cuadro de diálogo
        JOptionPane.showMessageDialog(rootPane, infoToShow.toString(), "Resumen", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_createRecordBtnActionPerformed

    /**
     * Método llamado cuando se hace clic en el botón para salir del programa.
     * Muestra un mensaje de confirmación antes de salir.
     * @param evt El evento que desencadenó la acción
     */
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Estás Seguro de que deseas salir?") == 0)
            this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * Método llamado cuando se hace clic en el botón para guardar el registro en pantalla
     * @param evt El evento que desencadenó la acción
     */
    private void saveRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRecordBtnActionPerformed
        // Guarda el registro en un archivo
        saveRecord(visitors);
    }//GEN-LAST:event_saveRecordBtnActionPerformed

    /**
     * Crea un registro de visitantes solicitando información al usuario a través de cuadros de diálogo.
     * Retorna un array de objetos Person con los datos de los visitantes.
     * Si ocurre un error durante la creación del registro, muestra un mensaje de error y retorna null.
     * @return Un array de objetos Person con los datos de los visitantes, o null si ocurre un error.
     */
    public Person[] createVisitorsRecord(){
        try{
            // Solicita al usuario la cantidad de personas que se registrarán
            int amountPeople = getNumberOfVisitors();

            //Verifica si se ingresó al menos una persona para el registro
            if(amountPeople <= 0){
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar al menos una persona para el registro");
                return null;
            }

            // Crea un array para almacenar los visitantes
            Person[] visitors = new Person[amountPeople];
            for(int i = 0; i < amountPeople; i++) {
                JOptionPane.showMessageDialog(rootPane, "Datos del visitante " + (i+1), "Visitante " + (i+1), JOptionPane.INFORMATION_MESSAGE);

                // Solicita la información de cada visitante
                String name = getVisitorName(i+1);
                int id = getVisitorId(i+1);
                short age = getVisitorsAge(i+1);
                char membershipCategory = getMembershipCategory(i+1);

                // Crea un objeto Person con la información del visitante y lo agrega al array de visitantes
                visitors[i] = new Person(name, id, age, membershipCategory);
            }
            return visitors; // Retorna el array de visitantes
        }catch(Exception e) {
            // Si ocurre un error durante la creación del registro, muestra un mensaje de error y retorna null
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al crear el registro de visitantes. Por favor, intenta nuevamente.");
            return null;
        }
    }

    // Métodos auxiliares para solicitar información de cada visitante
    private int getNumberOfVisitors(){
        return Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Número de Visitantes: " ));
    }
    private String getVisitorName(int index){return JOptionPane.showInputDialog(rootPane, String.format("Nombre del visitante %d", index));}
    private int getVisitorId(int index){return Integer.parseInt(JOptionPane.showInputDialog(rootPane, String.format("Número de Identificación del visitante %d", index)));}
    private short getVisitorsAge(int index){return Short.parseShort(JOptionPane.showInputDialog(rootPane, String.format("Edad del visitante %d", index)));}
    private char getMembershipCategory(int index){
        char membershipCategory;
        do{
            String input = JOptionPane.showInputDialog(rootPane, String.format("Categoría de Afilicación del visitante %d\nCategoría A: \"A\"\nCategoría B: \"B\"\nCategoría C: \"C\"\nNo está afiliado: \"N\" ", index));
            membershipCategory = input.toUpperCase().charAt(0);
            if (membershipCategory != 'A' && membershipCategory != 'B' && membershipCategory != 'C' && membershipCategory != 'N') {
                JOptionPane.showMessageDialog(rootPane, "Ingresaste un valor erróneo, intenta de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }while(membershipCategory != 'A' && membershipCategory != 'B' && membershipCategory != 'C' && membershipCategory != 'N');
        return membershipCategory;
    }
    /**
     * Elimina todas las filas existentes en el modelo de la tabla.
     * @param model El modelo de la tabla
     */
    public void removeAllRows(DefaultTableModel model){
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
    }

    /**
     * Agrega una nueva fila a la tabla con los datos del visitante.
     * @param model El modelo de la tabla
     * @param visitor El visitante cuyos datos se agregarán a la tabla
     */
    public void addRowToTable(DefaultTableModel model, Person visitor){
        Object[] newRowData = {visitor.getName(), visitor.getId(), visitor.getAge(), (visitor.getMembershipCategory() == 'N')?"No Aplica":visitor.getMembershipCategory(), visitor.getEntryValue()};
        model.addRow(newRowData);
    }

    /**
     * Guarda un registro de visitantes en un archivo seleccionado por el usuario.
     * Muestra un mensaje de confirmación una vez que el archivo se ha guardado correctamente.
     * Si no hay ningún registro para guardar o si se produce un error, muestra un mensaje de error correspondiente.
     * @param visitors El array de personas del registro de una visita.
     */
    public void saveRecord(Person[] visitors){
        try{
            // Verifica si hay registros para guardar en la tabla
            if(tableOutput.getRowCount() <= 0){
                throw new IOException("No hay registro para guardar");
            }

            // Crea un nuevo JFileChooser para que el usuario seleccione la ubicación y el nombre del archivo
            JFileChooser jFileChooser = new JFileChooser();
            int result = jFileChooser.showSaveDialog(rootPane);

            // Si el usuario selecciona un archivo y hace clic en "Guardar" correctamente
            if(result == JFileChooser.APPROVE_OPTION){
                File file = jFileChooser.getSelectedFile();

                // Crea una cadena de texto con los datos de los visitantes
                String data = parseRecordText(visitors);

                // Crea un FileWriter, un BufferedWriter y un PrintWriter para escribir los datos en el archivo
                try (FileWriter fileWriter = new FileWriter(file);
                     BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
                     PrintWriter writer = new PrintWriter(bufferedWriter)){

                    // Escribe los datos en el archivo
                    writer.write(data);

                    // Muestra un mensaje de confirmación
                    JOptionPane.showMessageDialog(rootPane, "Archivo guardado exitósamente");
                }
            }else{
                // Si el usuario cancela la operación, muestra un mensaje indicando que no se pudo seleccionar el archivo
                throw new IOException("No se pudo seleccionar el archivo");
            }
        }catch(IOException e){
            // Si se produce un error, muestra un mensaje de error con la descripción del problema
            JOptionPane.showMessageDialog(rootPane,"Error al guardar el archivo: " + e.getMessage());
        }
    }

    /**
     * Genera una cadena de texto formateada con la información de los visitantes para ser escrita en un archivo.
     * @param visitors El array de personas del registro de una visita.
     * @return Una cadena de texto con la información formateada de los visitantes.
     */
    public String parseRecordText(Person[] visitors){
        // StringBuilder para construir la cadena de texto
        StringBuilder data = new StringBuilder("Nombre\t| N° Identificación\t| Edad\t| Categoría\t| Entrada\n");

        // Itera sobre cada visitante para agregar su información formateada a la cadena de texto
        for (Person visitor : visitors) {
            // Agrega la información del visitante y un salto de línea al StringBuilder
            data.append(visitor.showInformation()).append("\n");
        }

        // Convierte el StringBuilder a una cadena de texto y la devuelve
        return data.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createRecordBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton saveRecordBtn;
    private javax.swing.JTable tableOutput;
    // End of variables declaration//GEN-END:variables
}
